name: build data

on:

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '15 10 * * *'    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: pip install csvkit
    - name: Build
      run: make

    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with:
        message: 'update'
        add: 'data/intermediate/all_plants.csv'
